name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: installGLFW
      run:  |
           sudo apt-get update
           sudo apt-get install cmake xorg-dev libglu1-mesa-dev
           sudo apt-get install libglfw3
           sudo apt-get install libglfw3-dev
    - name: build
      run: ./build.sh
